channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.13.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.0
  - pandas==2.2.2
  - pyyaml==6.0.1
  - requests==2.32.3
  - segmentation-models-pytorch==0.3.3
  - torch==2.3.0
name: mlflow-env
